trigger:
  - bicep
  
pool:
  vmImage: ubuntu-latest

variables:
  azSub: ARO-LZA
  location: eastus
  
  
jobs:  
  - job: Network_Hub
    displayName: Create Hub Network and Resources
    steps:
    - task: AzureCLI@2
      displayName: main deployment
      inputs:
        azureSubscription: $(azSub)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create -n "ARO-HUB-MAIN" \
          -l $(location) -f deployment/bicep/01-Network-Hub/main.bicep \
          -p deployment/bicep/01-Network-Hub/parameters-main.json

    - task: AzureCLI@2
      displayName: jumpbox deployment
      inputs:
        azureSubscription: $(azSub)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create -n "ARO-HUB-JUMPBOX" \
          -l $(location) -f deployment/bicep/01-Network-Hub/deploy-vm.bicep \
          -p deployment/bicep/01-Network-Hub/parameters-deploy-vm.json
    
    - task: AzureCLI@2
      displayName: update UDR
      inputs:
        azureSubscription: $(azSub)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create -n "ARO-HUB-UDR" \
          -l $(location) -f deployment/bicep/01-Network-Hub/updateUDR.bicep \
          -p deployment/bicep/01-Network-Hub/parameters-updateUDR.json

  - job: Network_spoke
    displayName: Create Spoke Network and Resources
    dependsOn: Network_Hub
    steps:
    - task: AzureCLI@2
      displayName: main deployment
      inputs:
        azureSubscription: $(azSub)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create -n "ARO-SPOKE-MAIN" \
          -l $(location) -f deployment/bicep/02-Network-Spoke/main.bicep \
          -p deployment/bicep/02-Network-Spoke/parameters-main.json

    - task: AzureCLI@2
      displayName: supporting deployment
      inputs:
        azureSubscription: $(azSub)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create -n "ARO-SPOKE-MAIN" \
          -l $(location) -f deployment/bicep/03-supporting/main.bicep \
          -p deployment/bicep/03-supporting/parameters-main.json
